title: Foto Terbaik Anda
description: TES 123 Nama saya muhammad Rizal Febrianto sedang menjalani kuliah di semester 5
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
